import { useGarageStore } from '../../store/useGarageStore'
import { PART_CATEGORY_LABELS, type PartCategory } from '../../types'

const CATEGORY_ICONS: Record<PartCategory, string> = {
  body_kits:  '🔧',
  wheels:     '⚙',
  suspension: '📐',
  exhaust:    '💨',
  spoilers:   '🏁',
  paint:      '🎨',
  lights:     '💡',
  engine_bay: '🔩',
  stance:     '📏',
}

function exportBuildSheet(
  carName: string,
  parts: { name: string; brand: string; category: PartCategory; price: number | null }[],
  paintLabel: string,
  total: number
) {
  const lines: string[] = [
    '══════════════════════════════════════════',
    '  APEX GARAGE — BUILD SHEET',
    '══════════════════════════════════════════',
    `  Vehicle : ${carName}`,
    `  Paint   : ${paintLabel}`,
    `  Date    : ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`,
    '──────────────────────────────────────────',
    '',
    '  INSTALLED PARTS',
    '──────────────────────────────────────────',
    ...parts.map(p =>
      `  [${PART_CATEGORY_LABELS[p.category].padEnd(18)}]  ${p.brand} — ${p.name}` +
      (p.price ? `   $${p.price.toLocaleString('en-US')}` : '')
    ),
    '',
    '──────────────────────────────────────────',
    `  ESTIMATED TOTAL           $${total.toLocaleString('en-US')}`,
    '══════════════════════════════════════════',
    '  Generated by APEX Garage — apexgarage.build',
    '',
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `apex-build-sheet-${Date.now()}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export default function BuildSummary() {
  const {
    summaryPanelOpen,
    toggleSummaryPanel,
    selectedParts,
    selectedCar,
    paintConfig,
    stanceConfig,
    wheelSize,
    resetBuild,
  } = useGarageStore()

  const installedParts = Object.values(selectedParts).filter(Boolean) as NonNullable<typeof selectedParts[keyof typeof selectedParts]>[]

  const total = installedParts.reduce((sum, p) => sum + (p?.priceMsrp ?? 0), 0)

  const paintLabel = (() => {
    if (paintConfig.wrapPreset) return `Wrap: ${paintConfig.wrapPreset.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}`
    return `${paintConfig.finishType.charAt(0).toUpperCase() + paintConfig.finishType.slice(1)} ${paintConfig.color.toUpperCase()}`
  })()

  const carName = selectedCar
    ? `${selectedCar.year} ${selectedCar.make} ${selectedCar.model}`
    : 'No car selected'

  return (
    <div
      className={`flex flex-col panel-glass shadow-panel transition-all duration-300 ${
        summaryPanelOpen ? 'w-64' : 'w-10'
      } h-full flex-shrink-0 relative overflow-hidden`}
    >
      {/* Expand/collapse toggle */}
      <button
        onClick={toggleSummaryPanel}
        className="absolute top-3 left-2 z-20 w-6 h-6 flex items-center justify-center text-shop-dim hover:text-shop-yellow transition-colors"
        title={summaryPanelOpen ? 'Collapse summary' : 'Expand build summary'}
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d={summaryPanelOpen ? 'M9 5l7 7-7 7' : 'M15 19l-7-7 7-7'}
          />
        </svg>
      </button>

      {summaryPanelOpen && (
        <>
          {/* Header */}
          <div className="pt-3 px-3 pb-2 border-b border-shop-border flex-shrink-0 mt-0">
            <div className="caution-border mb-2" />
            <div className="shop-header text-shop-yellow text-sm tracking-widest">BUILD SUMMARY</div>
            {selectedCar && (
              <div className="shop-mono text-shop-dim text-xs mt-0.5 truncate">{carName}</div>
            )}
          </div>

          {/* Parts list */}
          <div className="flex-1 overflow-y-auto p-2">
            {installedParts.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-32 text-center px-3">
                <div className="text-2xl mb-2 opacity-20">🔩</div>
                <div className="shop-mono text-shop-dim text-xs">No parts installed</div>
                <div className="shop-mono text-shop-dim text-xs mt-0.5 opacity-60">
                  Select parts from the left panel
                </div>
              </div>
            ) : (
              <div className="space-y-1">
                {installedParts.map(part => part && (
                  <div
                    key={part.id}
                    className="bg-shop-dark border border-shop-border rounded-sm p-2"
                  >
                    <div className="flex items-start gap-1.5">
                      <span className="text-xs mt-0.5">{CATEGORY_ICONS[part.category as PartCategory]}</span>
                      <div className="flex-1 min-w-0">
                        <div className="shop-header text-shop-white text-xs leading-snug truncate">{part.name}</div>
                        <div className="shop-mono text-shop-dim text-xs opacity-70 truncate">{part.brand}</div>
                      </div>
                    </div>
                    {part.priceMsrp && (
                      <div className="mt-1 shop-mono text-shop-yellow text-xs text-right">
                        ${part.priceMsrp.toLocaleString('en-US')}
                      </div>
                    )}
                  </div>
                ))}

                {/* Paint entry */}
                <div className="bg-shop-dark border border-shop-border rounded-sm p-2">
                  <div className="flex items-start gap-1.5">
                    <span className="text-xs mt-0.5">🎨</span>
                    <div className="flex-1 min-w-0">
                      <div className="shop-header text-shop-white text-xs leading-snug">Paint / Finish</div>
                      <div className="shop-mono text-shop-dim text-xs opacity-70 truncate">{paintLabel}</div>
                    </div>
                  </div>
                  <div className="mt-1 flex items-center justify-end gap-1.5">
                    <div
                      className="w-3 h-3 rounded-full border border-white/20"
                      style={{ backgroundColor: paintConfig.color }}
                    />
                  </div>
                </div>

                {/* Stance entry if not stock */}
                {(stanceConfig.rideHeight > 0 || stanceConfig.camber !== 0) && (
                  <div className="bg-shop-dark border border-shop-border rounded-sm p-2">
                    <div className="flex items-start gap-1.5">
                      <span className="text-xs mt-0.5">📏</span>
                      <div className="flex-1 min-w-0">
                        <div className="shop-header text-shop-white text-xs leading-snug">Stance</div>
                        <div className="shop-mono text-shop-dim text-xs opacity-70">
                          RH: {stanceConfig.rideHeight} · Camber: {stanceConfig.camber}° · {wheelSize}"
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Footer — total + actions */}
          <div className="flex-shrink-0 border-t border-shop-border p-3 space-y-2">
            <div className="flex items-center justify-between">
              <span className="shop-header text-shop-dim text-xs tracking-widest">TOTAL</span>
              <span className="shop-header text-shop-yellow text-base">
                ${total.toLocaleString('en-US')}
              </span>
            </div>

            {installedParts.length > 0 && (
              <>
                <button
                  onClick={() => exportBuildSheet(
                    carName,
                    installedParts
                      .filter(Boolean)
                      .map(p => ({
                        name: p!.name,
                        brand: p!.brand,
                        category: p!.category as PartCategory,
                        price: p!.priceMsrp,
                      })),
                    paintLabel,
                    total
                  )}
                  className="w-full btn-primary text-xs py-2"
                >
                  Export Build Sheet
                </button>
                <button
                  onClick={resetBuild}
                  className="w-full btn-ghost text-xs py-1.5"
                >
                  Clear All
                </button>
              </>
            )}
          </div>
        </>
      )}

      {/* Collapsed label */}
      {!summaryPanelOpen && (
        <div className="flex-1 flex items-center justify-center pt-8">
          <div
            className="shop-header text-shop-dim text-xs tracking-widest"
            style={{ writingMode: 'vertical-rl' }}
          >
            BUILD
          </div>
        </div>
      )}
    </div>
  )
}
